import fs from 'fs';
import path from 'path';
import { loadIndexFromSqlite } from '../storage/sqliteStore.js';

export interface InstructionOptions {
  format?: 'agents' | 'cursor' | 'claude';
  rootDir?: string;
}

export async function generateInstructionDoc(
  dbPath: string,
  options: InstructionOptions = {}
): Promise<string> {
  const rootDir = options.rootDir || path.dirname(path.dirname(dbPath));
  const format = options.format || 'agents';

  let indexData: any = null;
  if (fs.existsSync(dbPath)) {
    try {
      indexData = await loadIndexFromSqlite(dbPath);
    } catch {}
  }

  const sections: string[] = [];

  // Header
  if (format === 'cursor') {
    sections.push('# Cursor AI System Instructions (Auto-generated by dbci)\n');
  } else if (format === 'claude') {
    sections.push('# Claude / System AI Instructions (Auto-generated by dbci)\n');
  } else {
    sections.push('# Project Instructions & Codebase Context (Auto-generated by dbci)\n');
  }

  sections.push('> **Notice**: This file is auto-generated from live static analysis data and active project records. Manual updates to rules or context will be preserved across syncs.\n');

  // Section 1: AST Codebase Overview & DB Architecture Grounding
  sections.push('## 1. Codebase AST Grounding & Architecture Overview\n');
  if (indexData) {
    const fnCount = indexData.functions?.length || 0;
    const queryCount = indexData.queries?.length || 0;
    const clientCount = indexData.clients?.length || 0;

    sections.push(`- **Function Declarations Indexed**: ${fnCount}`);
    sections.push(`- **Database Queries Indexed**: ${queryCount}`);
    sections.push(`- **Database Clients Detected**: ${clientCount}`);

    if (indexData.clients && indexData.clients.length > 0) {
      sections.push('\n### Primary Database Connections Detected');
      const dbTypes = Array.from(new Set(indexData.clients.map((c: any) => c.dbType)));
      sections.push(`- Active DB Engines: \`${dbTypes.join('`, `')}\``);
    }

    if (indexData.queries && indexData.queries.length > 0) {
      sections.push('\n### Key Database Tables & Collections Interacted With');
      const tables = Array.from(new Set(indexData.queries.map((q: any) => q.table).filter(Boolean)));
      if (tables.length > 0) {
        sections.push(`- Tables/Collections: \`${tables.slice(0, 15).join('`, `')}\``);
      }
    }

    if (indexData.functions && indexData.functions.length > 0) {
      sections.push('\n### Key Exported Entrypoint Symbols');
      const sampleFns = indexData.functions.slice(0, 10);
      for (const fn of sampleFns) {
        sections.push(`- \`${fn.name}\` (${fn.file}:${fn.line})`);
      }
    }
  } else {
    sections.push('*No AST index found at `.dbci/index.sqlite`. Run `dbci scan` to ground this codebase.*');
  }

  sections.push('');

  // Section 2: Active Feature Plans
  sections.push('## 2. Active Feature Roadmap & Step Progress\n');
  if (indexData && indexData.plans && indexData.plans.length > 0) {
    for (const plan of indexData.plans) {
      sections.push(`### Plan: ${plan.title} [Status: ${plan.status.toUpperCase()}]`);
      sections.push(`- Goal: ${plan.goal}`);
      sections.push(`- Created By: ${plan.createdBy} at ${plan.createdAt}`);

      const relatedLogs = (indexData.planLogs || []).filter((l: any) => l.planId === plan.id);
      if (relatedLogs.length > 0) {
        sections.push(`- Progress Steps Completed (${relatedLogs.length}):`);
        for (const log of relatedLogs) {
          sections.push(`  • Step ${log.stepIndex}: ${log.description} [${log.status.toUpperCase()}]`);
        }
      }
      sections.push('');
    }
  } else {
    sections.push('*No active feature plans recorded. Use `dbci` plan routes or CLI to record plans.*\n');
  }

  // Section 3: Architecture Decision Records (ADRs)
  sections.push('## 3. Architecture Decision Records (ADRs)\n');
  if (indexData && indexData.decisions && indexData.decisions.length > 0) {
    for (const dec of indexData.decisions) {
      sections.push(`- **${dec.summary}** (Decided by ${dec.decidedBy} at ${dec.decidedAt})`);
      sections.push(`  *Rationale*: ${dec.rationale}`);
    }
    sections.push('');
  } else {
    sections.push('*No active architecture decisions recorded.*\n');
  }

  // Section 4: Rules & Guidelines
  sections.push('## 4. Project Rules & Guidelines\n');
  const gitRulesPath = path.join(rootDir, 'git', 'rules.md');
  const aiPermissionsPath = path.join(rootDir, 'permissions', 'ai-permissions.md');

  if (fs.existsSync(gitRulesPath)) {
    try {
      const gitRulesContent = fs.readFileSync(gitRulesPath, 'utf8');
      sections.push('### Git & Branching Rules');
      sections.push(gitRulesContent.trim());
      sections.push('');
    } catch {}
  }

  if (fs.existsSync(aiPermissionsPath)) {
    try {
      const permContent = fs.readFileSync(aiPermissionsPath, 'utf8');
      sections.push('### AI Permission & Write Safety Rules');
      sections.push(permContent.trim());
      sections.push('');
    } catch {}
  }

  // Section 5: Workflow Skills
  const skillsDir = path.join(rootDir, 'skills');
  if (fs.existsSync(skillsDir)) {
    try {
      const skillFiles = fs.readdirSync(skillsDir).filter(f => f.endsWith('.md') && f !== 'README.md');
      if (skillFiles.length > 0) {
        sections.push('## 5. Available Workflow Skills\n');
        for (const sf of skillFiles) {
          sections.push(`- \`${sf}\`: ${path.basename(sf, '.md')} workflow skill`);
        }
        sections.push('');
      }
    } catch {}
  }

  return sections.join('\n');
}
